# Generated by Django 5.2.5 on 2026-08-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_university_is_active_university_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='academics.academicunit')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['academic_unit', 'is_active'], name='academics_c_academi_c94b2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_unit', 'code'), name='unique_campus_code_per_academic_unit')],
            },
        ),
    ]
