# Generated by Django 5.2.5 on 2026-08-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='academics.career')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['career', 'is_active'], name='academics_s_career__a488bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('career', 'code'), name='unique_plan_code_per_career')],
            },
        ),
    ]
