# Generated by Django 5.2.5 on 2026-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studyarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='intermediate_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
