# Generated by Django 5.2.5 on 2026-09-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_studyplan_intermediate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('period', models.CharField(choices=[('1Q', '1er Cuatrimestre'), ('2Q', '2do Cuatrimestre'), ('1B', '1er Bimestre'), ('2B', '2do Bimestre'), ('3B', '3er Bimestre'), ('4B', '4to Bimestre'), ('AN', 'Anual')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.studyarea')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['study_area', 'is_active'], name='academics_s_study_a_d7f187_idx')],
                'constraints': [models.UniqueConstraint(fields=('study_area', 'code'), name='unique_subject_code_per_area')],
            },
        ),
    ]
