# Generated by Django 5.2.5 on 2026-09-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studyplan_duration_years_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=120)),
                ('subdiscipline', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['discipline', 'subdiscipline', 'specialty'],
                'constraints': [models.UniqueConstraint(fields=('discipline', 'subdiscipline', 'specialty'), name='unique_nomenclador_combo')],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='nomenclador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.nomenclador'),
        ),
    ]
