# Generated by Django 5.2.5 on 2026-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_nomenclador_subject_nomenclador'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='nomenclador_extra',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
