# Generated by Django 5.2.5 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subject_nomenclador_extra'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studyarea',
            constraint=models.UniqueConstraint(fields=('study_plan', 'name'), name='unique_area_name_per_plan'),
        ),
    ]
