# Generated by Django 5.2.5 on 2026-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_studyarea_unique_name_per_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_code_per_area',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
