# Generated by Django 5.2.5 on 2026-09-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_subject_code_unique_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
    ]
