# Generated by Django 5.2.5 on 2026-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_subject_order_by_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_subjects', models.ManyToManyField(blank=True, related_name='equivalences_as_new', to='academics.subject')),
                ('old_subjects', models.ManyToManyField(blank=True, related_name='equivalences_as_old', to='academics.subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
